### ISSUE TITLE
Error when pretraining the DAMSM model ?

### ISSUE THREAD

**Issue by ghost** [senmaoy/Recurrent-Affine-Transformation-for-Text-to-image-Synthesis#19]

**Comment by senmaoy** [comment]
It means that the list of img size is empty, it should be [256]. However, it's hard to directly know why an empty list is fed. Maybe the dataset hyperparameters are not correct.

**Comment by senmaoy** [comment]
It looks like your code is pointing to the second term in [299].  maybe you have set the image resolutions to be [256,128,64] in the code. try to set the image resolution [256]

**Comment by senmaoy** [comment]
> I just follow the instructions for the bird dataset setup in the [DM-GAN repo](https://github.com/MinfengZhu/DM-GAN), I don't know what causing the error. When I printed the `imsize`, I got `[299]`, is this correct ?

DM-GAN is tested by many users, there should be no problem. Hence, I recommend you delete all the code and data. Then clone the code again. Such an operation will avoid many strange errors
