### ISSUE TITLE
关于“花”数据集

### ISSUE THREAD

**Issue by 1hexf1** [senmaoy/Recurrent-Affine-Transformation-for-Text-to-image-Synthesis#2]
很棒的任务。作者您好，我最近刚接触到这个课题，找了很多程序都没有运行花数据集的程序，请问您可以公开花数据集的cfg文件或者是说一下怎么训练花的模型吗，十分感谢。

**Comment by senmaoy** [comment]
好嘞哥，马上给您共享

**Comment by 1hexf1** [comment]
十分感谢，太关键了。

**Comment by senmaoy** [comment]
哥您稍等哈，我这边也是自己处理出来的，比较脏，先整理一下方便大家用

**Comment by 1hexf1** [comment]
不着急不着急，您先弄着，辛苦了。

**Comment by senmaoy** [comment]
> 

哥，您看看能用吗？有bug我再改改

**Comment by 1hexf1** [comment]
当我运行花数据集时，会在datasat_flower.py的第105行报错：AttributeError: 'TextDataset' object has no attribute 'load_extra'
还有datasat_flower.py中的flower_cat_dic.pkl是什么呀，我没有找到。谢谢作者

**Comment by senmaoy** [comment]
尴尬，都删了就行。已经更新了

**Comment by senmaoy** [comment]
> 
我有个版本是搞成CUB一模一样的格式，混淆了

**Comment by 1hexf1** [comment]
再麻烦您一次，太不好意思了。datasat_flower.py的第201行：NameError: name 'train_names' is not defined。这里也报了错

**Comment by senmaoy** [comment]
> 再麻烦您一次，太不好意思了。datasat_flower.py的第201行：NameError: name 'train_names' is not defined。这里也报了错

我的我的，没调试就丢出来了

**Comment by senmaoy** [comment]
> 再麻烦您一次，太不好意思了。datasat_flower.py的第201行：NameError: name 'train_names' is not defined。这里也报了错

我的我的，您再试试？

**Comment by 1hexf1** [comment]
seed now is :  100
Load from:  /data01/hxf/text2image/data/flower/captions.pickle
Traceback (most recent call last):
  File "main.py", line 255, in <module>
    transform=image_transform)
  File "/data01/hhxf/Recurrent-Affine-Transformation-for-Text-to-image-Synthesis-main/code/datasat_flower.py", line 117, in __init__
    self.class_id = self.load_class_id(split_dir, len(self.filenames['img']))
TypeError: list indices must be integers or slices, not str
还是有点错误

**Comment by 1hexf1** [comment]
我跑起来了，太感谢了。刚才我们看到您更新了data文件，十分抱歉。 真是太强了您

**Comment by senmaoy** [comment]
> 我跑起来了，太感谢了。刚才我们看到您更新了data文件，十分抱歉。 真是太强了您
ojbk

**Comment by senmaoy** [comment]
> 

哥，您才是真的强👍

**Comment by 1hexf1** [comment]
您太客气了，我是刚接触这个方向的学生，希望以后还能和您进行交流，再次感谢！！

**Comment by senmaoy** [comment]
哥，您有问题，就尽管吩咐！我也是刚入行，随时欢迎交流，带我飞
