### ISSUE TITLE
Custom dataset 

### ISSUE THREAD

**Issue by ghost** [senmaoy/Recurrent-Affine-Transformation-for-Text-to-image-Synthesis#27]
In the [prepare dataset section](https://github.com/senmaoy/RAT-GAN#its-easy-to-train-on-your-own-datasets-similar-to-the-processing-for-flower-dataset), the line `Save captions.pickle under data_dir`, where is `data_dir` , does anyone know?

**Comment by senmaoy** [comment]
It's where the datas are stored.

**Comment by ghost** [comment]
How to train text encoder for custom dataset ?

**Comment by senmaoy** [comment]
It's here:   https://github.com/senmaoy/RAT-GAN/blob/main/code/pretrain_DAMSM.py

**Comment by ghost** [comment]
I mean the command line to train the text encoder, do you know ?

**Comment by senmaoy** [comment]
python  pretrain_DAMSM.py
But you need certain modifications
