### ISSUE TITLE
关于DAMSM中RNN这个类  和  FID这个指标

### ISSUE THREAD

**Issue by callmexiaowei** [senmaoy/Recurrent-Affine-Transformation-for-Text-to-image-Synthesis#3]
请问大哥   DAMSM中RNN这个类是不是没有使用啊？    还有FID这个指标是用DMGAN的代码测试的吗？用DMGAN的代码测试发现FID的指标对不上。

**Comment by senmaoy** [comment]
RNN是LSTM的简化版最后没用上，FID的代码我用的tackGAN的测试代码改的，对不上是差了多少

**Comment by senmaoy** [comment]
> 

我更新过代码和预训练模型，如果方便的话你可以试试更新一下代码，相同的inception 模型参数下，FID应该也是一样的。当然如果用了imagenet 预训练的参数 FID会下降很多

**Comment by callmexiaowei** [comment]
谢谢， 感谢作者回复   我是用DM-GAN的FID的测试代码测的FID值   IS值用您提供的代码测试的是没错的   我再更新一下代码重新试一下    谢谢！！！

**Comment by Cwj1212** [comment]
> 谢谢， 感谢作者回复 我是用DM-GAN的FID的测试代码测的FID值 IS值用您提供的代码测试的是没错的 我再更新一下代码重新试一下 谢谢！！！

您好，您是不是用的ImageNet上预训练的inception model测的cub的fid，cub上的fid您测得是10.2左右吗

**Comment by callmexiaowei** [comment]
> > 谢谢， 感谢作者回复 我是用DM-GAN的FID的测试代码测的FID值 IS值用您提供的代码测试的是没错的 我再更新一下代码重新试一下 谢谢！！！
> 
> 您好，您是不是用的ImageNet上预训练的inception model测的cub的fid，cub上的fid您测得是10.2左右吗

用DMGAN提供的代码测得，我也不知道什么预训练的，结果是15.57

**Comment by callmexiaowei** [comment]
> > 谢谢， 感谢作者回复 我是用DM-GAN的FID的测试代码测的FID值 IS值用您提供的代码测试的是没错的 我再更新一下代码重新试一下 谢谢！！！
> 
> 您好，您是不是用的ImageNet上预训练的inception model测的cub的fid，cub上的fid您测得是10.2左右吗

DMGAN那个FID测试代码，测试DMGAN生成的图片是对的。

**Comment by senmaoy** [comment]
> 

你用了多少张图

**Comment by Cwj1212** [comment]
> 

我也困惑这些，就是fid的测法不统一。你测得时候，生成图片是（测试集文本生成的图片），真实图片是（训练集的全部图片）吗？就是我前面这个括号里面的好像大家有点不统一。

**Comment by senmaoy** [comment]
你这个结果和2900张的图接近近，建议30000

**Comment by callmexiaowei** [comment]
> 你这个结果和2900张的图接近近，建议30000
生成了30000张图片   是没错的

**Comment by callmexiaowei** [comment]
> 

我测的FID是DMGAN的方法，结果差点，    希望作者大哥能针对性讲一下

**Comment by callmexiaowei** [comment]
> > 
> 
> 我也困惑这些，就是fid的测法不统一。你测得时候，生成图片是（测试集文本生成的图片吗？另外是一个文本生成一个图片还是一个文本生成多个图片以达到30000？），真实图片是（训练集的全部图片/数据集的全部图片/测试集的全部图片）吗？就是我前面这个括号里面的好像大家有点不统一。

我测的FID是DMGAN的方法，结果差点， 希望作者大哥能针对性讲一下

**Comment by senmaoy** [comment]
> 

是呀，路径换掉就行。
我用我主页的代码测是论文里的结果，DMGAN代码测的结果是10.2，那我有空再详细写一个教程吧，也许是随机波动？

**Comment by senmaoy** [comment]
> 
只要把路径换了就行了，顺序无所谓吧。我自己主页的代码结果和论文里的是一致的，13.91。DMGAN测试代码的结果是10.2， 会不会是随机波动？还有你的训练数据，测试数据分别是什么呢？

**Comment by 1hexf1** [comment]
> 你这个结果和2900张的图接近近，建议30000

作者大哥你好，我每次测试cub的时候都是生成29000张图片进行测试，是必须要三万才准确吗。

**Comment by senmaoy** [comment]
> > 你这个结果和2900张的图接近近，建议30000
> 
> 作者大哥你好，我每次测试cub的时候都是生成29000张图片进行测试，是必须要三万才准确吗。

代码里是不到3W的，3W左右增加图片，FID已经变化不大了

**Comment by 1hexf1** [comment]
> 

明白了 谢谢作者

**Comment by senmaoy** [comment]
> 根据大家的结果，在DM-GAN代码上用test caption+all real image  = 10.2;
test caption + test real image = 15.5; 这个做法似乎不是很统一，但大部分论文的结果是根据test caption + test real image报的。
我会在论文的第二版种更新这个结果

**Comment by callmexiaowei** [comment]
> 

大哥，您说的是生成图片和测试图片得出的FID为15.5，生成图片和所有图片FID为10.2     是这个意思吗？DMGAN给的是bird_val.npz这个文件啊

**Comment by senmaoy** [comment]
是的，这个文件里包含的就是测试的图片

**Comment by senmaoy** [comment]
根据我的实验结果，在CUB和OXford上测试集和训练集的效果差距较大，在COCO上则不明显

**Comment by callmexiaowei** [comment]
> 根据我的实验结果，在CUB和OXford上测试集和训练集的效果差距较大，在COCO上则不明显

感谢分享，明白点了     谢谢
