### ISSUE TITLE
Download flower dataset and extract the images to data/flower/. Raw text data of flower dataset is avaiable here. ？Here only have imgs and caption.pickle where is text.file?

### ISSUE THREAD

**Issue by hdcxqrc** [senmaoy/Recurrent-Affine-Transformation-for-Text-to-image-Synthesis#7]

**Comment by senmaoy** [comment]
I have already preprocessed the flower dataset, so you don't have to process it again. If you want to process the flower dataset on your own, you can download raw text data and process them according to the Readme. I have uploaded the raw text data to google drive and you can find the link in the Readme.

**Comment by hdcxqrc** [comment]
Where is the link of the raw text data？I really can't find it, I just found the same flower file after you added the ReadMe. I think you may had uploaded the wrong file(flower)

**Comment by senmaoy** [comment]
Forgive me.... 
I have updated the raw text data link.

**Comment by hdcxqrc** [comment]
This link seems to be the text of the bird dataset, please re-upload it, thanks

**Comment by senmaoy** [comment]
Dear hdcxqrc, thank you for your patience. Please check the raw text data again. I think it's okay now.

**Comment by hdcxqrc** [comment]
Thanks for your patience
